apply plugin: 'com.android.library'
apply from: '../shared/keepUnitySymbols.gradle'
apply from: '../shared/common.gradle'
**APPLY_PLUGINS**

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'androidx.core:core-ktx:1.9.0' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:6
    implementation 'androidx.lifecycle:lifecycle-process:2.6.1' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:5
    implementation 'com.google.code.gson:gson:2.8.5' // Assets/GoogleMobileAdsNative/Editor/GoogleMobileAdsNativeDependencies.xml:3
    implementation 'ir.tapsell.mediation.adapter:admob-unity:1.4.0-alpha02' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:8
    implementation 'ir.tapsell.mediation.adapter:applovin-unity:1.4.0-alpha02' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:9
    implementation 'ir.tapsell.mediation.adapter:legacy-unity:1.4.0-alpha02' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:7
    implementation 'ir.tapsell.mediation.adapter:mintegral-unity:1.4.0-alpha02' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:10
    implementation 'ir.tapsell:tapsell-unity:1.4.0-alpha02' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:4
// Android Resolver Dependencies End
**DEPS**}

// Android Resolver Exclusions Start
android {
  packaging {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/armeabi-v7a/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
  }
}
// Android Resolver Exclusions End
android {
    namespace "com.unity3d.player"
    ndkPath "**NDKPATH**"
    ndkVersion "**NDKVERSION**"
    compileSdk **APIVERSION**
    buildToolsVersion "**BUILDTOOLS**"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdk **MINSDK**
        targetSdk **TARGETSDK**
        ndk {
            abiFilters **ABIFILTERS**
            debugSymbolLevel **DEBUGSYMBOLLEVEL**
        }
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
**DEFAULT_CONFIG_SETUP**
    }

    lint {
        abortOnError false
    }

    androidResources {
        noCompress = **BUILTIN_NOCOMPRESS** + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING**
}
**IL_CPP_BUILD_SETUP**
**SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**
