apply plugin: 'com.android.library'
**APPLY_PLUGINS**

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'androidx.core:core-ktx:1.9.0' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:6
    implementation 'androidx.lifecycle:lifecycle-process:2.6.1' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:5
    implementation 'com.google.code.gson:gson:2.8.5' // Assets/GoogleMobileAdsNative/Editor/GoogleMobileAdsNativeDependencies.xml:3
    implementation 'ir.tapsell.mediation.adapter:admob-unity:1.4.0-alpha01' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:8
    implementation 'ir.tapsell.mediation.adapter:applovin-unity:1.4.0-alpha01' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:9
    implementation 'ir.tapsell.mediation.adapter:chartboost-unity:1.4.0-alpha01' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:10
    implementation 'ir.tapsell.mediation.adapter:fyber-unity:1.4.0-alpha01' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:11
    implementation 'ir.tapsell.mediation.adapter:ironsource-unity:1.4.0-alpha01' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:12
    implementation 'ir.tapsell.mediation.adapter:legacy-unity:1.4.0-alpha01' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:7
    implementation 'ir.tapsell.mediation.adapter:liftoff-unity:1.4.0-alpha01' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:13
    implementation 'ir.tapsell.mediation.adapter:mintegral-unity:1.4.0-alpha01' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:14
    implementation 'ir.tapsell:tapsell-unity:1.4.0-alpha01' // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:4
// Android Resolver Dependencies End
**DEPS**}

android {
    ndkPath "**NDKPATH**"
    namespace "com.unity3d.player"

    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
**DEFAULT_CONFIG_SETUP**
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = **BUILTIN_NOCOMPRESS** + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING_OPTIONS**
}
**IL_CPP_BUILD_SETUP**
**SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**
