pluginManagement {
    repositories {
        **ARTIFACTORYREPOSITORY**
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

include ':launcher', ':unityLibrary'
**INCLUDES**

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        **ARTIFACTORYREPOSITORY**
        google()
        mavenCentral()
// Android Resolver Repos Start
        def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
        maven {
            url "https://maven.tapsell.ir/" // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:16
        }
        maven {
            url "https://maven.google.com/" // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:16
        }
        maven {
            url "https://repo1.maven.org/maven2/" // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:16
        }
        maven {
            url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea" // Assets/Tapsell/Mediation/Editor/TapsellMediationDependencies.xml:16
        }
        mavenLocal()
// Android Resolver Repos End
        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
    }
}
